/**
 * Shared type definitions for the dsh-oauth-plugin.
 * @module dsh-oauth-plugin/types
 */

/** A signed-in user identity. */
export interface UserInfo {
  /** Stable user identifier. */
  readonly id: string
  /** Display name or email. */
  readonly displayName: string
  /** Auth token returned by the remote API. */
  readonly token: string
}

/** Request body for the username/password login endpoint. */
export interface LoginRequest {
  /** Username or email. */
  username: string
  /** Password. */
  password: string
}

/** Response body for a successful login. */
export interface LoginResponse {
  /** The authenticated user info. */
  user: UserInfo
  /** Optional expiration in seconds; null means no expiry. */
  expiresIn: number | null
}

/** Error response from the auth API. */
export interface AuthError {
  /** Machine-readable error code. */
  code: 'INVALID_CREDENTIALS' | 'UNAUTHORIZED' | 'RATE_LIMITED' | 'SERVER_ERROR'
  /** Human-readable message. */
  message: string
}

/**
 * Session↔user mapping persisted on disk.
 * Keyed by sessionId → userId.
 */
export interface SessionUserMapping {
  /** sessionId → userId */
  [sessionId: string]: string
}

/**
 * Plugin configuration.
 */
export interface Config {
  /**
   * Base URL of the auth API. Examples:
   * - `http://localhost:3000/api/auth`
   * - `https://auth.example.com`
   */
  apiUrl: string
  /**
   * Path appended to apiUrl for the login endpoint.
   * Default: `/login`
   */
  loginPath?: string
  /**
   * Path appended to apiUrl for the verify/me endpoint.
   * Default: `/me`
   */
  mePath?: string
  /**
   * Path appended to apiUrl for the logout endpoint.
   * Default: `/logout`
   */
  logoutPath?: string
  /**
   * File inside $DSH_HOME to persist session↔user mappings.
   * Default: `.oauth-sessions.json`
   */
  sessionMapFile?: string
  /**
   * Whether to enable the WeChat Website App scan-login tab.
   * Default: `false`
   */
  wechatEnabled?: boolean
  /**
   * Whether to enable mock mode: admin/admin logs in without a remote API.
   * When true, apiUrl is unused for login and `/api/auth/me` returns a fixed user.
   * Default: `false`
   */
  mockEnabled?: boolean
  /**
   * WeChat Open Platform Website App AppID.
   * Required when `wechatEnabled` is true.
   */
  wechatAppId?: string
  /**
   * WeChat Open Platform Website App AppSecret. Server-side only, never
   * exposed to the client.
   */
  wechatAppSecret?: string
  /**
   * OAuth redirect URI, must match the callback domain configured in the
   * WeChat Open Platform and point at this plugin's callback route
   * (`/api/auth/wechat/callback`).
   */
  wechatRedirectUri?: string
  /**
   * OAuth `state` validity in ms. The `state` guards the callback against
   * CSRF and is single-use. Default: 600000 (10 min, same as the WeChat
   * `code` lifetime).
   */
  wechatStateTtlMs?: number
  /**
   * Whether to enable WeChat quick login (fast_login parameter in wxLogin.js).
   * When true (default), users on supported WeChat desktop clients can log in
   * without scanning the QR code. Requires WeChat 3.9.11+ on Windows or
   * 4.0.0+ on macOS, with the client logged in and not locked.
   */
  wechatFastLogin?: boolean
}

export const DEFAULT_CONFIG: Required<Omit<Config, 'apiUrl'>> = {
  loginPath: '/login',
  mePath: '/me',
  logoutPath: '/logout',
  sessionMapFile: '.oauth-sessions.json',
  wechatEnabled: false,
  mockEnabled: false,
  wechatAppId: '',
  wechatAppSecret: '',
  wechatRedirectUri: '',
  wechatStateTtlMs: 600000,
  wechatFastLogin: true,
}

/** Response body for the WeChat login bootstrap endpoint. */
export interface WeChatConfigResponse {
  /** Whether WeChat login is configured and enabled. */
  enabled: boolean
  /** WeChat Open Platform Website App AppID (client-safe). */
  appId: string
  /**
   * OAuth redirect URI. The client passes this to wxLogin.js as
   * `redirect_uri`; WeChat redirects there with `code` and `state` after
   * the user confirms the scan.
   */
  redirectUri: string
  /**
   * Single-use CSRF `state`, generated by the server for this QR session.
   * WeChat echoes it back on the callback, where the server validates it.
   */
  state: string
  /** OAuth scope, always `snsapi_login` for website-app login. */
  scope: string
  /**
   * Whether quick login is enabled. When true, WeChat desktop clients
   * (3.9.11+ Windows / 4.0.0+ macOS) may show a quick-login button
   * instead of requiring a full QR scan.
   */
  fastLogin: boolean
}

/** Query parameters on the WeChat OAuth callback (`/api/auth/wechat/callback`). */
export interface WeChatCallbackQuery {
  /** Authorization code, valid for 10 minutes, single-use. */
  code: string
  /** The CSRF state generated by the bootstrap endpoint. */
  state: string
}
